### ISSUE TITLE
Signing in with google doesn't work for me: "This browser or app may not be secure"

### ISSUE THREAD

**Issue by andyDoucette** [yudax42/askai#1]
I love the idea of using chatgpt from the command line!  :)  Thanks so much for writing this tool.

Here is what is happening for me so far.

I try to log in with with `askai login`, and clicking on `log in with google`.  I enter my email address, and click on next and I get this message:

```
Couldn’t sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.
```

Do you know why this might be happening?  Do you have any suggestions?

**Comment by yudax42** [comment]
I have identified that the issue you are experiencing is a bug caused by the use of a headless controlled browser for authentication. For security reasons, Google does not allow this type of authentication. I have updated the package to use a library that interacts with ChatGPT using the private API instead. This will not only resolve the bug you are experiencing, but it will also make the process faster. Please update the CLI to the latest version and try again. Thank you.

**Comment by andyDoucette** [comment]
Thanks so much!  It's working now.  :)
