### ISSUE TITLE
Error: "Could not find prompt area"

### ISSUE THREAD

**Issue by andyDoucette** [yudax42/askai#2]
I made an email/password login to get past the last issue.

This is what happens when I try to run the tool:

```
$ askai 'does this work?'
⡐ Connecting to ChatGPT...Could not find prompt area
```

Looking at the HTML and the source code, it seems that PROMPT_AREA_SELECTOR in config.ts needs to be updated somehow:

It currently reads:
`PROMPT_AREA_SELECTOR:
    "div[class*='PromptTextarea__TextareaWrapper'] textarea",`, but I don't see any PromptTextarea__TextareaWrapper in the html of the ChatGPT form when I go there manually.  Not sure what the new selector should be, but if they did indeed change the HTML, I think this should break for you too so hopefully you can provide an update when you get a chance?

Thanks again for making this! :)

**Comment by yudax42** [comment]
Hi @andyDoucette,
It appears that they have updated and removed the CSS classes, which is why you are getting the error. I have shipped a fix for it. To fix the issue, you just need to update the CLI to the latest version. Then, you can find your ChatGPT token in the cookies and use the `askai login` command to add it. The token is named __Secure-next-auth.session-token. please let me know if you have any other questions

**Comment by andyDoucette** [comment]
Thanks so much!  It's working now.  :)
